version: "3.8"
services:
  practica_backend:
    container_name: practica_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8500:8500"
    networks:
      - microservices
    environment:
      DB_DIALECT: "postgres"
      DB_USER: "root"
      DB_PASS: "root"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_NAME: "practica_backend"
      REST_PORT: 8500
networks:
  microservices:
    name: microservices
